// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.20.3
// source: schema.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CfgGameMode int32

const (
	CfgGameMode_CfgGameMode_EMPTY_PLACEHOLDER CfgGameMode = 0
	CfgGameMode_CfgGameMode_Classic           CfgGameMode = 1
	CfgGameMode_CfgGameMode_Ranked            CfgGameMode = 2
)

// Enum value maps for CfgGameMode.
var (
	CfgGameMode_name = map[int32]string{
		0: "CfgGameMode_EMPTY_PLACEHOLDER",
		1: "CfgGameMode_Classic",
		2: "CfgGameMode_Ranked",
	}
	CfgGameMode_value = map[string]int32{
		"CfgGameMode_EMPTY_PLACEHOLDER": 0,
		"CfgGameMode_Classic":           1,
		"CfgGameMode_Ranked":            2,
	}
)

func (x CfgGameMode) Enum() *CfgGameMode {
	p := new(CfgGameMode)
	*p = x
	return p
}

func (x CfgGameMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CfgGameMode) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[0].Descriptor()
}

func (CfgGameMode) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[0]
}

func (x CfgGameMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CfgGameMode.Descriptor instead.
func (CfgGameMode) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

type CfgRoomState int32

const (
	CfgRoomState_CfgRoomState_EMPTY_PLACEHOLDER CfgRoomState = 0
	CfgRoomState_CfgRoomState_Idle              CfgRoomState = 1
	CfgRoomState_CfgRoomState_Matching          CfgRoomState = 2
	CfgRoomState_CfgRoomState_Playing           CfgRoomState = 3
	CfgRoomState_CfgRoomState_Finished          CfgRoomState = 4
)

// Enum value maps for CfgRoomState.
var (
	CfgRoomState_name = map[int32]string{
		0: "CfgRoomState_EMPTY_PLACEHOLDER",
		1: "CfgRoomState_Idle",
		2: "CfgRoomState_Matching",
		3: "CfgRoomState_Playing",
		4: "CfgRoomState_Finished",
	}
	CfgRoomState_value = map[string]int32{
		"CfgRoomState_EMPTY_PLACEHOLDER": 0,
		"CfgRoomState_Idle":              1,
		"CfgRoomState_Matching":          2,
		"CfgRoomState_Playing":           3,
		"CfgRoomState_Finished":          4,
	}
)

func (x CfgRoomState) Enum() *CfgRoomState {
	p := new(CfgRoomState)
	*p = x
	return p
}

func (x CfgRoomState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CfgRoomState) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[1].Descriptor()
}

func (CfgRoomState) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[1]
}

func (x CfgRoomState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CfgRoomState.Descriptor instead.
func (CfgRoomState) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{1}
}

type Global struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerName      string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	MaxRoomPlayer   int32                  `protobuf:"varint,2,opt,name=max_room_player,json=maxRoomPlayer,proto3" json:"max_room_player,omitempty"`
	MatchTimeoutSec int32                  `protobuf:"varint,3,opt,name=match_timeout_sec,json=matchTimeoutSec,proto3" json:"match_timeout_sec,omitempty"`
	TurnTimeoutSec  int32                  `protobuf:"varint,4,opt,name=turn_timeout_sec,json=turnTimeoutSec,proto3" json:"turn_timeout_sec,omitempty"`
	BoardSize       int32                  `protobuf:"varint,5,opt,name=board_size,json=boardSize,proto3" json:"board_size,omitempty"`
	AllowUndo       bool                   `protobuf:"varint,6,opt,name=allow_undo,json=allowUndo,proto3" json:"allow_undo,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Global) Reset() {
	*x = Global{}
	mi := &file_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Global) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Global) ProtoMessage() {}

func (x *Global) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Global.ProtoReflect.Descriptor instead.
func (*Global) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Global) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Global) GetMaxRoomPlayer() int32 {
	if x != nil {
		return x.MaxRoomPlayer
	}
	return 0
}

func (x *Global) GetMatchTimeoutSec() int32 {
	if x != nil {
		return x.MatchTimeoutSec
	}
	return 0
}

func (x *Global) GetTurnTimeoutSec() int32 {
	if x != nil {
		return x.TurnTimeoutSec
	}
	return 0
}

func (x *Global) GetBoardSize() int32 {
	if x != nil {
		return x.BoardSize
	}
	return 0
}

func (x *Global) GetAllowUndo() bool {
	if x != nil {
		return x.AllowUndo
	}
	return false
}

type Tbglobal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataList      []*Global              `protobuf:"bytes,1,rep,name=data_list,json=dataList,proto3" json:"data_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tbglobal) Reset() {
	*x = Tbglobal{}
	mi := &file_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tbglobal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tbglobal) ProtoMessage() {}

func (x *Tbglobal) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tbglobal.ProtoReflect.Descriptor instead.
func (*Tbglobal) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Tbglobal) GetDataList() []*Global {
	if x != nil {
		return x.DataList
	}
	return nil
}

var File_schema_proto protoreflect.FileDescriptor

var file_schema_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x63, 0x66, 0x67, 0x22, 0xe5, 0x01, 0x0a, 0x06, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x26, 0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6d, 0x61, 0x78, 0x52, 0x6f, 0x6f,
	0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x11, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x53, 0x65, 0x63, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74,
	0x75, 0x72, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x63, 0x12, 0x1d, 0x0a,
	0x0a, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x75, 0x6e, 0x64, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x6e, 0x64, 0x6f, 0x22, 0x38, 0x0a, 0x08, 0x54,
	0x62, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x12, 0x2c, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x66, 0x67,
	0x2e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x42, 0x02, 0x10, 0x00, 0x52, 0x08, 0x64, 0x61, 0x74,
	0x61, 0x4c, 0x69, 0x73, 0x74, 0x2a, 0x61, 0x0a, 0x0b, 0x43, 0x66, 0x67, 0x47, 0x61, 0x6d, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x1d, 0x43, 0x66, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x4d,
	0x6f, 0x64, 0x65, 0x5f, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x5f, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x48,
	0x4f, 0x4c, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x66, 0x67, 0x47, 0x61,
	0x6d, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x5f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x63, 0x10, 0x01,
	0x12, 0x16, 0x0a, 0x12, 0x43, 0x66, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x5f,
	0x52, 0x61, 0x6e, 0x6b, 0x65, 0x64, 0x10, 0x02, 0x2a, 0x99, 0x01, 0x0a, 0x0c, 0x43, 0x66, 0x67,
	0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x1e, 0x43, 0x66, 0x67,
	0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x5f,
	0x50, 0x4c, 0x41, 0x43, 0x45, 0x48, 0x4f, 0x4c, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x15, 0x0a,
	0x11, 0x43, 0x66, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x49, 0x64,
	0x6c, 0x65, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x66, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x5f, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12,
	0x18, 0x0a, 0x14, 0x43, 0x66, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x5f,
	0x50, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x66, 0x67,
	0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x10, 0x04, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_schema_proto_rawDescOnce sync.Once
	file_schema_proto_rawDescData []byte
)

func file_schema_proto_rawDescGZIP() []byte {
	file_schema_proto_rawDescOnce.Do(func() {
		file_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)))
	})
	return file_schema_proto_rawDescData
}

var file_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schema_proto_goTypes = []any{
	(CfgGameMode)(0),  // 0: cfg.CfgGameMode
	(CfgRoomState)(0), // 1: cfg.CfgRoomState
	(*Global)(nil),    // 2: cfg.global
	(*Tbglobal)(nil),  // 3: cfg.Tbglobal
}
var file_schema_proto_depIdxs = []int32{
	2, // 0: cfg.Tbglobal.data_list:type_name -> cfg.global
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_schema_proto_init() }
func file_schema_proto_init() {
	if File_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_proto_goTypes,
		DependencyIndexes: file_schema_proto_depIdxs,
		EnumInfos:         file_schema_proto_enumTypes,
		MessageInfos:      file_schema_proto_msgTypes,
	}.Build()
	File_schema_proto = out.File
	file_schema_proto_goTypes = nil
	file_schema_proto_depIdxs = nil
}
