
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 对局模式定义
 */
type CfgGameMode int32
const (
    /**
     * 标准对局
     */
    CfgGameMode_Classic CfgGameMode = 1;
    /**
     * 天梯匹配
     */
    CfgGameMode_Ranked CfgGameMode = 2;
)

