
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 房间状态定义
 */
type CfgRoomState int32
const (
    /**
     * 等待玩家进入
     */
    CfgRoomState_Idle CfgRoomState = 1;
    /**
     * 等待匹配完成
     */
    CfgRoomState_Matching CfgRoomState = 2;
    /**
     * 棋局进行中
     */
    CfgRoomState_Playing CfgRoomState = 3;
    /**
     * 棋局已结束
     */
    CfgRoomState_Finished CfgRoomState = 4;
)

