
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type global struct {
    ServerName string
    MaxRoomPlayer int32
    MatchTimeoutSec int32
    TurnTimeoutSec int32
    BoardSize int32
    AllowUndo bool
}

const TypeId_global = -1243020381

func (*global) GetTypeId() int32 {
    return -1243020381
}

func Newglobal(_buf map[string]interface{}) (_v *global, err error) {
    _v = &global{}
    { var _ok_ bool; var __json_server_name__ interface{}; if __json_server_name__, _ok_ = _buf["server_name"]; !_ok_ || __json_server_name__ == nil { err = errors.New("server_name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_server_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.ServerName = __x__ }}
    { var _ok_ bool; var __json_max_room_player__ interface{}; if __json_max_room_player__, _ok_ = _buf["max_room_player"]; !_ok_ || __json_max_room_player__ == nil { err = errors.New("max_room_player error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_max_room_player__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.MaxRoomPlayer = __x__ }}
    { var _ok_ bool; var __json_match_timeout_sec__ interface{}; if __json_match_timeout_sec__, _ok_ = _buf["match_timeout_sec"]; !_ok_ || __json_match_timeout_sec__ == nil { err = errors.New("match_timeout_sec error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_match_timeout_sec__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.MatchTimeoutSec = __x__ }}
    { var _ok_ bool; var __json_turn_timeout_sec__ interface{}; if __json_turn_timeout_sec__, _ok_ = _buf["turn_timeout_sec"]; !_ok_ || __json_turn_timeout_sec__ == nil { err = errors.New("turn_timeout_sec error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_turn_timeout_sec__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.TurnTimeoutSec = __x__ }}
    { var _ok_ bool; var __json_board_size__ interface{}; if __json_board_size__, _ok_ = _buf["board_size"]; !_ok_ || __json_board_size__ == nil { err = errors.New("board_size error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_board_size__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.BoardSize = __x__ }}
    { var _ok_ bool; var __json_allow_undo__ interface{}; if __json_allow_undo__, _ok_ = _buf["allow_undo"]; !_ok_ || __json_allow_undo__ == nil { err = errors.New("allow_undo error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_allow_undo__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.AllowUndo = __x__ }}
    return
}

