// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.20.3
// source: auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthLoginREQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`                         // 账号标识
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,2,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"` // 设备信息
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                             // 登录token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLoginREQ) Reset() {
	*x = AuthLoginREQ{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLoginREQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLoginREQ) ProtoMessage() {}

func (x *AuthLoginREQ) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLoginREQ.ProtoReflect.Descriptor instead.
func (*AuthLoginREQ) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthLoginREQ) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AuthLoginREQ) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *AuthLoginREQ) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 认证登录消息返回
type AuthLoginRSP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *HttpError             `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`                                             // 错误码 0: 成功 1 2 3,
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`                                     // 账号
	Session       string                 `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`                                     // 认证服session
	TimeZone      int32                  `protobuf:"varint,4,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`                  // 服务器时区
	GlobalFlags   uint64                 `protobuf:"varint,6,opt,name=global_flags,json=globalFlags,proto3" json:"global_flags,omitempty"`         // 游戏全局flags
	CreatedDays   int32                  `protobuf:"varint,7,opt,name=created_days,json=createdDays,proto3" json:"created_days,omitempty"`         // 创建天数
	ShowWaterMark bool                   `protobuf:"varint,9,opt,name=show_water_mark,json=showWaterMark,proto3" json:"show_water_mark,omitempty"` // 是否显示水印
	Ip            string                 `protobuf:"bytes,10,opt,name=ip,proto3" json:"ip,omitempty"`                                              // ip
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLoginRSP) Reset() {
	*x = AuthLoginRSP{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLoginRSP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLoginRSP) ProtoMessage() {}

func (x *AuthLoginRSP) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLoginRSP.ProtoReflect.Descriptor instead.
func (*AuthLoginRSP) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthLoginRSP) GetErr() *HttpError {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *AuthLoginRSP) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AuthLoginRSP) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *AuthLoginRSP) GetTimeZone() int32 {
	if x != nil {
		return x.TimeZone
	}
	return 0
}

func (x *AuthLoginRSP) GetGlobalFlags() uint64 {
	if x != nil {
		return x.GlobalFlags
	}
	return 0
}

func (x *AuthLoginRSP) GetCreatedDays() int32 {
	if x != nil {
		return x.CreatedDays
	}
	return 0
}

func (x *AuthLoginRSP) GetShowWaterMark() bool {
	if x != nil {
		return x.ShowWaterMark
	}
	return false
}

func (x *AuthLoginRSP) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// 使用角色进入区服
type AuthUseRoleREQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`                         // 认证服session
	Sid           int32                  `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`                                // 服务器ID
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,3,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"` // 设备信息
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                               // 玩家名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUseRoleREQ) Reset() {
	*x = AuthUseRoleREQ{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUseRoleREQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUseRoleREQ) ProtoMessage() {}

func (x *AuthUseRoleREQ) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUseRoleREQ.ProtoReflect.Descriptor instead.
func (*AuthUseRoleREQ) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthUseRoleREQ) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *AuthUseRoleREQ) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *AuthUseRoleREQ) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *AuthUseRoleREQ) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AuthUseRoleRSP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *HttpError             `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`                   // 错误码
	Gid           int64                  `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`                  // 角色id
	Addr          *ServerAddr            `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`                 // 服务器地址
	ForbidStart   int64                  `protobuf:"varint,4,opt,name=forbidStart,proto3" json:"forbidStart,omitempty"`  // 开始禁号时间
	ForbidEnd     int64                  `protobuf:"varint,5,opt,name=forbidEnd,proto3" json:"forbidEnd,omitempty"`      // 结束禁号时间
	ForbidReason  string                 `protobuf:"bytes,6,opt,name=forbidReason,proto3" json:"forbidReason,omitempty"` // 禁止登录说明
	TimeZone      int32                  `protobuf:"varint,7,opt,name=timeZone,proto3" json:"timeZone,omitempty"`        // 服务器时区
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUseRoleRSP) Reset() {
	*x = AuthUseRoleRSP{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUseRoleRSP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUseRoleRSP) ProtoMessage() {}

func (x *AuthUseRoleRSP) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUseRoleRSP.ProtoReflect.Descriptor instead.
func (*AuthUseRoleRSP) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthUseRoleRSP) GetErr() *HttpError {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *AuthUseRoleRSP) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *AuthUseRoleRSP) GetAddr() *ServerAddr {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *AuthUseRoleRSP) GetForbidStart() int64 {
	if x != nil {
		return x.ForbidStart
	}
	return 0
}

func (x *AuthUseRoleRSP) GetForbidEnd() int64 {
	if x != nil {
		return x.ForbidEnd
	}
	return 0
}

func (x *AuthUseRoleRSP) GetForbidReason() string {
	if x != nil {
		return x.ForbidReason
	}
	return ""
}

func (x *AuthUseRoleRSP) GetTimeZone() int32 {
	if x != nil {
		return x.TimeZone
	}
	return 0
}

// 服务器地址
type ServerAddr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerAddr) Reset() {
	*x = ServerAddr{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAddr) ProtoMessage() {}

func (x *ServerAddr) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAddr.ProtoReflect.Descriptor instead.
func (*ServerAddr) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ServerAddr) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ServerAddr) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// 玩家登陆
type LoginBySessionREQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           int64                  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`                                // 玩家id
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`                         // 重连session
	Reconnect     bool                   `protobuf:"varint,3,opt,name=reconnect,proto3" json:"reconnect,omitempty"`                    // 是否重连
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,4,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"` // 设备数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginBySessionREQ) Reset() {
	*x = LoginBySessionREQ{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginBySessionREQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginBySessionREQ) ProtoMessage() {}

func (x *LoginBySessionREQ) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginBySessionREQ.ProtoReflect.Descriptor instead.
func (*LoginBySessionREQ) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *LoginBySessionREQ) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *LoginBySessionREQ) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *LoginBySessionREQ) GetReconnect() bool {
	if x != nil {
		return x.Reconnect
	}
	return false
}

func (x *LoginBySessionREQ) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

// 玩家重连/切服
type LoginReconnectREQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           int64                  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`        // 玩家id
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"` // 重连session
	Ack           int32                  `protobuf:"varint,3,opt,name=ack,proto3" json:"ack,omitempty"`        //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReconnectREQ) Reset() {
	*x = LoginReconnectREQ{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReconnectREQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReconnectREQ) ProtoMessage() {}

func (x *LoginReconnectREQ) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReconnectREQ.ProtoReflect.Descriptor instead.
func (*LoginReconnectREQ) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *LoginReconnectREQ) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *LoginReconnectREQ) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *LoginReconnectREQ) GetAck() int32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

// 玩家登陆
type LoginBySessionRSP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           ERROR                  `protobuf:"varint,1,opt,name=err,proto3,enum=pb.ERROR" json:"err,omitempty"`                         // 错误码 LOGIN_IN_QUEUE 已在排队中, LOGIN_EXIT_QUEUE 已退出排队
	Main          *Gamer                 `protobuf:"bytes,2,opt,name=main,proto3" json:"main,omitempty"`                                      // 玩家主信息
	ForbidStart   int64                  `protobuf:"varint,4,opt,name=forbid_start,json=forbidStart,proto3" json:"forbid_start,omitempty"`    // 开始禁号时间
	ForbidEnd     int64                  `protobuf:"varint,5,opt,name=forbid_end,json=forbidEnd,proto3" json:"forbid_end,omitempty"`          // 结束禁号时间
	ForbidReason  string                 `protobuf:"bytes,6,opt,name=forbid_reason,json=forbidReason,proto3" json:"forbid_reason,omitempty"`  // 禁止登录说明
	TimeZone      int32                  `protobuf:"varint,7,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`             // 服务器时区
	RegisterTime  int64                  `protobuf:"varint,8,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"` // 角色注册时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginBySessionRSP) Reset() {
	*x = LoginBySessionRSP{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginBySessionRSP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginBySessionRSP) ProtoMessage() {}

func (x *LoginBySessionRSP) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginBySessionRSP.ProtoReflect.Descriptor instead.
func (*LoginBySessionRSP) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *LoginBySessionRSP) GetErr() ERROR {
	if x != nil {
		return x.Err
	}
	return ERROR_SUCCESS
}

func (x *LoginBySessionRSP) GetMain() *Gamer {
	if x != nil {
		return x.Main
	}
	return nil
}

func (x *LoginBySessionRSP) GetForbidStart() int64 {
	if x != nil {
		return x.ForbidStart
	}
	return 0
}

func (x *LoginBySessionRSP) GetForbidEnd() int64 {
	if x != nil {
		return x.ForbidEnd
	}
	return 0
}

func (x *LoginBySessionRSP) GetForbidReason() string {
	if x != nil {
		return x.ForbidReason
	}
	return ""
}

func (x *LoginBySessionRSP) GetTimeZone() int32 {
	if x != nil {
		return x.TimeZone
	}
	return 0
}

func (x *LoginBySessionRSP) GetRegisterTime() int64 {
	if x != nil {
		return x.RegisterTime
	}
	return 0
}

type LoginSyncNTF struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 是否同步完成
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginSyncNTF) Reset() {
	*x = LoginSyncNTF{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginSyncNTF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSyncNTF) ProtoMessage() {}

func (x *LoginSyncNTF) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSyncNTF.ProtoReflect.Descriptor instead.
func (*LoginSyncNTF) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *LoginSyncNTF) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 玩家登出
type LoginOutREQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           int64                  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginOutREQ) Reset() {
	*x = LoginOutREQ{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginOutREQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginOutREQ) ProtoMessage() {}

func (x *LoginOutREQ) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginOutREQ.ProtoReflect.Descriptor instead.
func (*LoginOutREQ) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *LoginOutREQ) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type LoginOutRSP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginOutRSP) Reset() {
	*x = LoginOutRSP{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginOutRSP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginOutRSP) ProtoMessage() {}

func (x *LoginOutRSP) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginOutRSP.ProtoReflect.Descriptor instead.
func (*LoginOutRSP) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

// 服务器关闭
type ServerCloseNTF struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                         // 0 正常关闭 1 维护
	ShutTime      int64                  `protobuf:"varint,2,opt,name=shut_time,json=shutTime,proto3" json:"shut_time,omitempty"` // 关闭时间
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCloseNTF) Reset() {
	*x = ServerCloseNTF{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCloseNTF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCloseNTF) ProtoMessage() {}

func (x *ServerCloseNTF) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCloseNTF.ProtoReflect.Descriptor instead.
func (*ServerCloseNTF) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ServerCloseNTF) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ServerCloseNTF) GetShutTime() int64 {
	if x != nil {
		return x.ShutTime
	}
	return 0
}

func (x *ServerCloseNTF) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

var file_auth_proto_rawDesc = string([]byte{
	0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x0c, 0x41,
	0x75, 0x74, 0x68, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x45, 0x51, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xfe, 0x01, 0x0a,
	0x0c, 0x41, 0x75, 0x74, 0x68, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x53, 0x50, 0x12, 0x1f, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x48, 0x74, 0x74, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x7a, 0x6f, 0x6e, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x46, 0x6c, 0x61,
	0x67, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x61,
	0x79, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x44, 0x61, 0x79, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x77, 0x61,
	0x74, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d,
	0x73, 0x68, 0x6f, 0x77, 0x57, 0x61, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x72, 0x6b, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x81, 0x01,
	0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x45, 0x51,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x0b,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0xe7, 0x01, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x53, 0x50, 0x12, 0x1f, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x66,
	0x6f, 0x72, 0x62, 0x69, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x66, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x66, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x45, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x66, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x45, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x66,
	0x6f, 0x72, 0x62, 0x69, 0x64, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x66, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x22, 0x30, 0x0a, 0x0a, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x8e, 0x01,
	0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x45, 0x51, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x2f, 0x0a,
	0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x51,
	0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x52, 0x45, 0x51, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x63,
	0x6b, 0x22, 0xf8, 0x01, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x53, 0x50, 0x12, 0x1b, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x12, 0x1d, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x72, 0x52, 0x04, 0x6d,
	0x61, 0x69, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x5f, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x66, 0x6f, 0x72, 0x62, 0x69,
	0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6f, 0x72, 0x62, 0x69, 0x64,
	0x5f, 0x65, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x66, 0x6f, 0x72, 0x62,
	0x69, 0x64, 0x45, 0x6e, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x5f,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x6f,
	0x72, 0x62, 0x69, 0x64, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x5f, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74,
	0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x0c,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x79, 0x6e, 0x63, 0x4e, 0x54, 0x46, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x1f, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x75, 0x74,
	0x52, 0x45, 0x51, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x67, 0x69, 0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x75,
	0x74, 0x52, 0x53, 0x50, 0x22, 0x59, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x4e, 0x54, 0x46, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68,
	0x75, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73,
	0x68, 0x75, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42,
	0x21, 0x5a, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x70, 0x62, 0xaa, 0x02, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x2e, 0x4e, 0x65, 0x74, 0x2e,
	0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_auth_proto_goTypes = []any{
	(*AuthLoginREQ)(nil),      // 0: pb.AuthLoginREQ
	(*AuthLoginRSP)(nil),      // 1: pb.AuthLoginRSP
	(*AuthUseRoleREQ)(nil),    // 2: pb.AuthUseRoleREQ
	(*AuthUseRoleRSP)(nil),    // 3: pb.AuthUseRoleRSP
	(*ServerAddr)(nil),        // 4: pb.ServerAddr
	(*LoginBySessionREQ)(nil), // 5: pb.LoginBySessionREQ
	(*LoginReconnectREQ)(nil), // 6: pb.LoginReconnectREQ
	(*LoginBySessionRSP)(nil), // 7: pb.LoginBySessionRSP
	(*LoginSyncNTF)(nil),      // 8: pb.LoginSyncNTF
	(*LoginOutREQ)(nil),       // 9: pb.LoginOutREQ
	(*LoginOutRSP)(nil),       // 10: pb.LoginOutRSP
	(*ServerCloseNTF)(nil),    // 11: pb.ServerCloseNTF
	(*DeviceInfo)(nil),        // 12: pb.DeviceInfo
	(*HttpError)(nil),         // 13: pb.HttpError
	(ERROR)(0),                // 14: pb.ERROR
	(*Gamer)(nil),             // 15: pb.Gamer
}
var file_auth_proto_depIdxs = []int32{
	12, // 0: pb.AuthLoginREQ.device_info:type_name -> pb.DeviceInfo
	13, // 1: pb.AuthLoginRSP.err:type_name -> pb.HttpError
	12, // 2: pb.AuthUseRoleREQ.device_info:type_name -> pb.DeviceInfo
	13, // 3: pb.AuthUseRoleRSP.err:type_name -> pb.HttpError
	4,  // 4: pb.AuthUseRoleRSP.addr:type_name -> pb.ServerAddr
	12, // 5: pb.LoginBySessionREQ.device_info:type_name -> pb.DeviceInfo
	14, // 6: pb.LoginBySessionRSP.err:type_name -> pb.ERROR
	15, // 7: pb.LoginBySessionRSP.main:type_name -> pb.Gamer
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	file_common_proto_init()
	file_error_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
