// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.20.3
// source: micro.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Act int32

const (
	Act_ACT_NONE Act = 0
	// -------------------------------------------认证服消息开始----------------------------------------------------
	Act_AUTH_PING     Act = 1 // ping消息
	Act_AUTH_USE_ROLE Act = 2 // 使用角色
	Act_AUTH_NOTICE   Act = 3 // 登录页公告
	Act_AUTH_CHECK    Act = 4 // 检查是否允许进入区服
	Act_AUTH_LOGIN    Act = 5 // 登录认证
	// ----------登录----------------
	Act_LOGIN_BY_SESSION Act = 7 // 通过session登录
	Act_LOGIN_SYNC       Act = 8 // 同步登录状态
)

// Enum value maps for Act.
var (
	Act_name = map[int32]string{
		0: "ACT_NONE",
		1: "AUTH_PING",
		2: "AUTH_USE_ROLE",
		3: "AUTH_NOTICE",
		4: "AUTH_CHECK",
		5: "AUTH_LOGIN",
		7: "LOGIN_BY_SESSION",
		8: "LOGIN_SYNC",
	}
	Act_value = map[string]int32{
		"ACT_NONE":         0,
		"AUTH_PING":        1,
		"AUTH_USE_ROLE":    2,
		"AUTH_NOTICE":      3,
		"AUTH_CHECK":       4,
		"AUTH_LOGIN":       5,
		"LOGIN_BY_SESSION": 7,
		"LOGIN_SYNC":       8,
	}
)

func (x Act) Enum() *Act {
	p := new(Act)
	*p = x
	return p
}

func (x Act) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Act) Descriptor() protoreflect.EnumDescriptor {
	return file_micro_proto_enumTypes[0].Descriptor()
}

func (Act) Type() protoreflect.EnumType {
	return &file_micro_proto_enumTypes[0]
}

func (x Act) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Act.Descriptor instead.
func (Act) EnumDescriptor() ([]byte, []int) {
	return file_micro_proto_rawDescGZIP(), []int{0}
}

type Cmd int32

const (
	Cmd_CMD_NONE Cmd = 0
	Cmd_LOGIN    Cmd = 1 // 登录
	Cmd_AUTH     Cmd = 2 // 验证
	Cmd_MAIN     Cmd = 3 // 主界面
	Cmd_NOTIFY   Cmd = 4 // 通知
	Cmd_MATCH    Cmd = 5 // 匹配
	Cmd_ROOM     Cmd = 6 // 房间
)

// Enum value maps for Cmd.
var (
	Cmd_name = map[int32]string{
		0: "CMD_NONE",
		1: "LOGIN",
		2: "AUTH",
		3: "MAIN",
		4: "NOTIFY",
		5: "MATCH",
		6: "ROOM",
	}
	Cmd_value = map[string]int32{
		"CMD_NONE": 0,
		"LOGIN":    1,
		"AUTH":     2,
		"MAIN":     3,
		"NOTIFY":   4,
		"MATCH":    5,
		"ROOM":     6,
	}
)

func (x Cmd) Enum() *Cmd {
	p := new(Cmd)
	*p = x
	return p
}

func (x Cmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cmd) Descriptor() protoreflect.EnumDescriptor {
	return file_micro_proto_enumTypes[1].Descriptor()
}

func (Cmd) Type() protoreflect.EnumType {
	return &file_micro_proto_enumTypes[1]
}

func (x Cmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cmd.Descriptor instead.
func (Cmd) EnumDescriptor() ([]byte, []int) {
	return file_micro_proto_rawDescGZIP(), []int{1}
}

// 玩家状态
type GamerStatus int32

const (
	GamerStatus_OFFLINE  GamerStatus = 0 // 离线
	GamerStatus_ONLINE   GamerStatus = 1 // 在线
	GamerStatus_OMATCH   GamerStatus = 2 // 匹配中
	GamerStatus_INCOMING GamerStatus = 3 // 加入
	GamerStatus_FIGHTING GamerStatus = 4 // 比赛中
	GamerStatus_EXITING  GamerStatus = 5 // 退出
	GamerStatus_INTERACT GamerStatus = 6 // 互动
)

// Enum value maps for GamerStatus.
var (
	GamerStatus_name = map[int32]string{
		0: "OFFLINE",
		1: "ONLINE",
		2: "OMATCH",
		3: "INCOMING",
		4: "FIGHTING",
		5: "EXITING",
		6: "INTERACT",
	}
	GamerStatus_value = map[string]int32{
		"OFFLINE":  0,
		"ONLINE":   1,
		"OMATCH":   2,
		"INCOMING": 3,
		"FIGHTING": 4,
		"EXITING":  5,
		"INTERACT": 6,
	}
)

func (x GamerStatus) Enum() *GamerStatus {
	p := new(GamerStatus)
	*p = x
	return p
}

func (x GamerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GamerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_micro_proto_enumTypes[2].Descriptor()
}

func (GamerStatus) Type() protoreflect.EnumType {
	return &file_micro_proto_enumTypes[2]
}

func (x GamerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GamerStatus.Descriptor instead.
func (GamerStatus) EnumDescriptor() ([]byte, []int) {
	return file_micro_proto_rawDescGZIP(), []int{2}
}

var File_micro_proto protoreflect.FileDescriptor

var file_micro_proto_rawDesc = string([]byte{
	0x0a, 0x0b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x2a, 0x8c, 0x01, 0x0a, 0x03, 0x41, 0x63, 0x74, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x43, 0x54,
	0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x55, 0x54, 0x48, 0x5f,
	0x50, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x55,
	0x53, 0x45, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x55, 0x54,
	0x48, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x55,
	0x54, 0x48, 0x5f, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x55,
	0x54, 0x48, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x05, 0x12, 0x14, 0x0a, 0x10, 0x4c, 0x4f,
	0x47, 0x49, 0x4e, 0x5f, 0x42, 0x59, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x07,
	0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x53, 0x59, 0x4e, 0x43, 0x10, 0x08,
	0x2a, 0x53, 0x0a, 0x03, 0x43, 0x6d, 0x64, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4d, 0x44, 0x5f, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x41, 0x55, 0x54, 0x48, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41,
	0x49, 0x4e, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x10, 0x04,
	0x12, 0x09, 0x0a, 0x05, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x52,
	0x4f, 0x4f, 0x4d, 0x10, 0x06, 0x2a, 0x69, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x4f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x43,
	0x4f, 0x4d, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x49, 0x47, 0x48, 0x54,
	0x49, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x58, 0x49, 0x54, 0x49, 0x4e, 0x47,
	0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x41, 0x43, 0x54, 0x10, 0x06,
	0x42, 0x24, 0x5a, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x62, 0xaa, 0x02, 0x0e, 0x46, 0x75, 0x73, 0x61, 0x6e, 0x65, 0x72, 0x2e,
	0x4e, 0x65, 0x74, 0x2e, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_micro_proto_rawDescOnce sync.Once
	file_micro_proto_rawDescData []byte
)

func file_micro_proto_rawDescGZIP() []byte {
	file_micro_proto_rawDescOnce.Do(func() {
		file_micro_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_micro_proto_rawDesc), len(file_micro_proto_rawDesc)))
	})
	return file_micro_proto_rawDescData
}

var file_micro_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_micro_proto_goTypes = []any{
	(Act)(0),         // 0: pb.Act
	(Cmd)(0),         // 1: pb.Cmd
	(GamerStatus)(0), // 2: pb.GamerStatus
}
var file_micro_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_micro_proto_init() }
func file_micro_proto_init() {
	if File_micro_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_micro_proto_rawDesc), len(file_micro_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_micro_proto_goTypes,
		DependencyIndexes: file_micro_proto_depIdxs,
		EnumInfos:         file_micro_proto_enumTypes,
	}.Build()
	File_micro_proto = out.File
	file_micro_proto_goTypes = nil
	file_micro_proto_depIdxs = nil
}
